export default [
  'Battery in Use',
  'Circuit Integrity Failed',
  'High Respiratory Rate',
  'High FiO2',
  'High PEEP',
  'High Plateau Pressure',
  'High Peak Pressure',
  'Low Inspiratory Pressure',
  'Low FiO2',
  'Low PEEP',
  'Low Plateau Pressure',
  'Oxygen Failure',
  'Low Tidal Volume',
  'High Tidal Volume',
  'System Reset - Please Recheck FiO2/PEEP/Minute Ventilation Settings',
  'Low Minute Ventilation',
  'High Minute Ventilation',
  'Patient Vent Circuit Disconnected',
  'Mechanical Integrity Failed',
  'Homing not Done',
  '96 Hours of Operation',
  'Flow Sensor Disconnected',
  'Pressure Sensor Disconnected',
  'Oxygen Sensor Disconnected',
  'Low Respiratory Rate',
  'Safe Mode',
];
